# Generated by Django 3.2.7 on 2021-10-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like_counter',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
